-- Supabase migration: create eBay PH clone tables with profile, products, orders, and payments

create table if not exists public.user_profile (
    user_id int generated by default as identity primary key,
    user_firstname varchar(50) not null,
    user_lastname varchar(50) not null,
    user_phonenumber varchar(20),
    user_email varchar(100) unique not null,
    user_password varchar(255) not null
);

create table if not exists public.address (
    address_id int generated by default as identity primary key,
    user_id int references public.user_profile(user_id) on delete cascade,
    address_street varchar(100),
    address_city varchar(50),
    address_country varchar(50),
    address_postalcode varchar(15)
);

create table if not exists public.product (
    product_id int generated by default as identity primary key,
    product_name varchar(100) not null,
    product_brand varchar(50),
    product_price decimal(10,2) not null check (product_price >= 0),
    product_category varchar(50),
    product_condition varchar(30),
    product_description text,
    seller_id int references public.user_profile(user_id)
);

create table if not exists public.orderlist (
    order_id int generated by default as identity primary key,
    user_id int references public.user_profile(user_id),
    order_date date default current_date,
    address_id int references public.address(address_id)
);

create table if not exists public.order_product (
    order_id int references public.orderlist(order_id) on delete cascade,
    product_id int references public.product(product_id) on delete cascade,
    orderproduct_quantity int not null check (orderproduct_quantity > 0),
    primary key (order_id, product_id)
);

create table if not exists public.feedback (
    feedback_id int generated by default as identity primary key,
    user_id int references public.user_profile(user_id),
    feedback_comment text,
    feedback_type varchar(30) check (feedback_type in ('positive', 'neutral', 'negative'))
);

create table if not exists public.payment (
    payment_id int generated by default as identity primary key,
    order_id int references public.orderlist(order_id),
    payment_card_number varchar(25),
    payment_cvv varchar(5),
    payment_date date default current_date
);

create table if not exists public.shipment (
    shipment_id int generated by default as identity primary key,
    order_id int references public.orderlist(order_id),
    shipment_expecteddate date,
    shipment_deliverydate date,
    shipment_date date
);
